### ISSUE TITLE
Unclear how to add global variables and `image: ...`

### ISSUE THREAD

**Issue by hansbogert** [bgamari/dhall-gitlab-ci#3]
Just wandered into the world of dhall less than a day ago, this is awesome stuff. I'm not sure how complete this repo is deemed to be, but how can I do the following:

```yaml
---
image: tmaier/docker-compose


variables:
  COMPOSE_FILE: 'docker-compose.yml'

...
```

Thanks!
